# Generated by Django 5.1.4 on 2025-02-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0005_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='plan',
            field=models.CharField(choices=[('D', 'Diet plan'), ('E', 'Exercise plan')], default='D', max_length=50),
        ),
    ]
