# Generated by Django 5.1.4 on 2025-02-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0006_appointment_descriptions_appointment_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='plan',
            field=models.CharField(choices=[('Diet', 'Diet plan'), ('Exercise', 'Exercise plan')], default='D', max_length=50),
        ),
    ]
