# Generated by Django 5.1.4 on 2025-03-01 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0009_appointmentanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentanswer',
            name='user',
        ),
        migrations.AddField(
            model_name='appointmentanswer',
            name='reps',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentanswer',
            name='sets',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plan', to='coaches.appointment')),
            ],
        ),
        migrations.AddField(
            model_name='appointmentanswer',
            name='workout_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='coaches.workoutplan'),
        ),
    ]
