# Generated by Django 5.1.4 on 2025-03-01 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0010_remove_appointmentanswer_user_appointmentanswer_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachposts',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='coaches.coach'),
        ),
    ]
