# Generated by Django 5.1.4 on 2025-03-03 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_regularuser_date_of_birth_remove_user_age_and_more'),
        ('coaches', '0011_alter_coachposts_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentanswer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='appointmentanswer',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='appointmentanswer',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='appointment',
        ),
        migrations.AddField(
            model_name='appointmentanswer',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='coaches.exercises'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_workout_plan', to='accounts.regularuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointmentanswer',
            name='workout_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='coaches.workoutplan'),
            preserve_default=False,
        ),
    ]
