# Generated by Django 5.1.4 on 2025-03-03 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0012_remove_appointmentanswer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='workoutplan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_plan', to='coaches.workoutplan'),
        ),
    ]
