# Generated by Django 5.1.4 on 2025-04-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0015_remove_appointment_answered_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='appointments/', verbose_name='appointment Image'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='plan',
            field=models.CharField(choices=[('Diet', 'Diet plan'), ('Exercise', 'Exercise plan')], default='Diet', max_length=50),
        ),
    ]
