# Generated by Django 5.1.4 on 2025-04-13 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0016_appointment_image_alter_appointment_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='appointments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='appointment Image'),
        ),
    ]
