# Generated by Django 5.1.4 on 2025-04-13 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_regularuser_date_of_birth_remove_user_age_and_more'),
        ('coaches', '0017_alter_appointment_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created']},
        ),
        migrations.AlterUniqueTogether(
            name='workoutplan',
            unique_together={('user', 'name')},
        ),
    ]
